service: get-info

provider:
  name: aws
  runtime: nodejs6.10
  profile: exortech

functions:
  getInfo:
    handler: service/get-info.handler
    events:
      - http: get urlinfo/1/{proxy+}

package:
  exclude:
    - ./**
  include:
    - service/**
